name-template: 'v$RESOLVED_VERSION 💎'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'deps'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🎨 Style & Design'
    labels:
      - 'style'
      - 'design'
      - 'ui'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'docs'

template: |
  ## 💎 ERIFY™ World Release Notes
  
  ### What's Changed
  
  $CHANGES
  
  ### ✨ Highlights
  
  This release brings luxury-grade improvements to the ERIFY™ ecosystem with enhanced workflows, documentation, and developer experience.
  
  ### 🤝 Contributors
  
  Thanks to all contributors who made this release possible!
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
  
  ---
  
  *⚡ From the ashes to the stars ✨ - Building the future of digital luxury*