---
title: "Add New Feature"
labels: ["good first issue", "feature"]
description: |
  **Task Description**: Describe the feature you want to add.

  **Acceptance Criteria**: Define what will make this feature complete.

  **Steps to Reproduce**: N/A
