name: "Follow-Up: Bottom Nav & CTA Glow"
description: "Finalize anchors and SVG icons for the landing page bottom navigation + CTA."
title: "[Follow-Up] Finalize Bottom Nav & CTA Glow"
labels: ["follow-up", "frontend", "erify-glow", "priority:medium"]
assignees:
  - erify-world
body:
  - type: markdown
    attributes:
      value: "💎🔥 Use this form to finalize anchors and SVG icons after PR #16."

  - type: input
    id: page_path
    attributes:
      label: Landing page path
      placeholder: pages/index.html (or actual path)
    validations:
      required: true

  - type: dropdown
    id: confirm_sections
    attributes:
      label: Confirm sections included
      multiple: true
      options:
        - Home
        - Crest
        - Neon
        - Legacy
        - Contact
    validations:
      required: true

  - type: textarea
    id: anchors
    attributes:
      label: Anchor IDs
      description: "Provide the finalized ids (e.g., #home, #crest, #neon, #legacy, #contact). One per line in the order of the nav."
      placeholder: |
        #home
        #crest
        #neon
        #legacy
        #contact
    validations:
      required: true

  - type: textarea
    id: icon_map
    attributes:
      label: Icon mapping (SVG file names)
      description: "Map each slot to an SVG (e.g., home.svg, crest.svg…). One per line matching the anchors order."
      placeholder: |
        home.svg
        crest.svg
        neon.svg
        legacy.svg
        contact.svg
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / acceptance criteria
      value: |
        - Replace placeholder links with finalized anchors
        - Swap emoji placeholders with SVG icons
        - Verify hover/active glow works on mobile & desktop
        - Confirm CTA `.card--glow` renders above nav safely

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Anchors wired and tested
        - label: SVGs imported and referenced
        - label: Mobile safe-area & z-index verified
        - label: Lighthouse pass (no major regressions)
