---
name: 🟢 ERIFY™ Smoke Test Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - '.github/workflows/*smoke-test*.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  add-smoke-test-checklist:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Add ERIFY™ Smoke Test Review Checklist
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            // Check if checklist comment already exists
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number
            });
            
            const checklistExists = comments.data.some(comment =>
              comment.body.includes('🟢 ERIFY™ Smoke Test Review Checklist')
            );
            
            if (!checklistExists) {
              const checklistBody = `# 🟢 ERIFY™ Smoke Test Review Checklist
            
            ## 🧪 Workflow Validation
            - [ ] **Trigger Configuration** - \`workflow_dispatch\` allows manual execution
            - [ ] **Runner Environment** - Uses \`ubuntu-latest\` for consistency
            - [ ] **Job Naming** - Clear and descriptive job names (\`alive\`)
            - [ ] **Step Structure** - Logical flow from sanity check to secret validation
            
            ## 🔐 Secret Management Review
            - [ ] **CF_API_TOKEN** - Cloudflare API authentication check implemented
            - [ ] **CF_STREAM_SIGNING_KEY** - Cloudflare Stream signing key validation
            - [ ] **SLACK_WEBHOOK_URL** - Slack notification endpoint verification
            - [ ] **DISCORD_WEBHOOK_URL** - Discord notification endpoint validation
            - [ ] **TEAMS_WEBHOOK_URL** - Microsoft Teams notification endpoint check
            - [ ] **Non-blocking Design** - Missing secrets reported as notices, not failures
            
            ## 🛡️ Security & Best Practices
            - [ ] **No Secret Exposure** - Secrets are only checked for presence, never logged
            - [ ] **Safe Failure Mode** - Workflow succeeds even with missing secrets
            - [ ] **Informative Output** - Clear ✅ indicators for present secrets
            - [ ] **Notice Messages** - Appropriate \`::notice::\` syntax for missing secrets
            
            ## 🚀 Deployment Readiness
            - [ ] **Workflow File Location** - Correctly placed in \`.github/workflows/\`
            - [ ] **YAML Syntax** - Valid YAML formatting and structure
            - [ ] **Manual Testing** - Can be triggered manually for smoke testing
            - [ ] **Environment Agnostic** - Works across different deployment contexts
            
            ## 📝 Documentation & Maintenance
            - [ ] **Clear Purpose** - Workflow serves as health check for ERIFY™ ecosystem
            - [ ] **Maintainable Code** - Individual secret checks for easy modification
            - [ ] **Descriptive Messaging** - Output clearly indicates GitHub Actions status
            
            ---
            
            **Review Status**: ⏳ Pending | ✅ Approved | ❌ Changes Requested
            
            **Reviewer**: <!-- Add reviewer name -->
            **Review Date**: <!-- Add review date -->
            
            ---
            
            *This checklist was automatically generated for smoke test workflow reviews. Please check off completed items as you review the PR.*`;
            
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: checklistBody
              });
              
              core.info('Added ERIFY™ Smoke Test Review Checklist to PR #' + pr.number);
            } else {
              core.info('ERIFY™ Smoke Test Review Checklist already exists on PR #' + pr.number);
            }