---
name: 🧭 Triage

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-triage:
    # Skip drafts and common bots
    if: >
      github.event.pull_request.draft == false &&
      !contains(fromJson('["dependabot[bot]","github-actions[bot]"]'),
               github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
      - name: Add `needs-review` label
        uses: actions/github-script@v7
        with:
          script: |
            const label = 'needs-review';
            const pr = context.payload.pull_request;
            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: [label]
              });
            } catch (e) {
              core.warning(`Label skipped: ${e.message}`);
            }

      - name: Assign to @erify-world
        uses: actions/github-script@v7
        with:
          script: |
            const assignee = 'erify-world';
            const pr = context.payload.pull_request;

            const already = (pr.assignees || []).some(a => a.login === assignee);
            if (!already) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: [assignee]
              });
            }
---

